In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier  

In [2]:
data = pd.read_csv('M30_EURUSD.csv')
data.head()

C:\Users\ihkar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (5,6,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,50,51,55,56,58,59,61,62,64,65,67,68,70,71,73,74,76,77,79,80,82,83,85,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,139,140,142,143,145,146,147,148,149,150,151,152,153,154,155,156,158,160,162,164,166,168,170,172,174,176,178,179,180,181,183,185,186,188,189,191,192,194,195,197,198,200,201,203,204,206,207,209,210,212,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,30

time     open     high      low    close ind_5 ind_6 ind_7  \
0  2017.06.26 04:00  1.11894  1.11959  1.11894  1.11942     ?     ?     ?   
1  2017.06.26 04:30  1.11943  1.11960  1.11913  1.11942     ?     ?     ?   
2  2017.06.26 05:00  1.11940  1.11943  1.11891  1.11922     ?     ?     ?   
3  2017.06.26 05:30  1.11924  1.11968  1.11919  1.11957     ?     ?     ?   
4  2017.06.26 06:00  1.11955  1.11955  1.11914  1.11926     ?     ?     ?   

  ind_8 ind_9  ... 80_signal 90_signal 100_signal 120_signal 140_signal  \
0     ?     ?  ...       BUY       BUY        BUY        BUY        BUY   
1     ?     ?  ...       BUY       BUY        BUY        BUY        BUY   
2     ?     ?  ...       BUY       BUY        BUY        BUY        BUY   
3     ?     ?  ...       BUY       BUY        BUY        BUY        BUY   
4     ?     ?  ...       BUY       BUY        BUY        BUY        BUY   

  160_signal 180_signal 200_signal 220_signal 240_signal  
0        BUY        BUY        BUY        BUY        BUY  
1        BUY        BUY        BUY        BUY        BUY  
2        BUY        BUY        BUY        BUY        BUY  
3        BUY        BUY        BUY        BUY        BUY  
4        BUY        BUY        BUY        BUY        BUY  

[5 rows x 445 columns]

In [3]:
# soru işaretleri olan satırlar veriden silindi.
data = data.replace("?", np.nan)
data = data.dropna()
data.head()

time     open     high      low    close ind_5 ind_6 ind_7  \
2001  2017.08.22 20:30  1.17502  1.17538  1.17478  1.17505   -20   -19  NONE   
2002  2017.08.22 21:00  1.17505  1.17531  1.17492  1.17500   -20   -20  NONE   
2003  2017.08.22 21:30  1.17496  1.17599  1.17487  1.17583   -19   -20   BUY   
2004  2017.08.22 22:00  1.17582  1.17627  1.17565  1.17600   -17   -19  NONE   
2005  2017.08.22 22:30  1.17600  1.17630  1.17595  1.17603   -13   -17  NONE   

                   ind_8              ind_9  ... 80_signal 90_signal  \
2001   7.142857142857143  92.85714285714286  ...       BUY       BUY   
2002                 0.0  85.71428571428571  ...       BUY       BUY   
2003  35.714285714285715  78.57142857142857  ...       BUY       BUY   
2004  28.571428571428573  71.42857142857143  ...       BUY       BUY   
2005  21.428571428571427  64.28571428571429  ...       BUY       BUY   

     100_signal 120_signal 140_signal 160_signal 180_signal 200_signal  \
2001        BUY        BUY        BUY        BUY        BUY        BUY   
2002        BUY        BUY        BUY        BUY        BUY        BUY   
2003        BUY        BUY        BUY        BUY        BUY        BUY   
2004        BUY        BUY        BUY        BUY        BUY        BUY   
2005        BUY        BUY        BUY        BUY        BUY        BUY   

     220_signal 240_signal  
2001        BUY        BUY  
2002        BUY        BUY  
2003        BUY        BUY  
2004        BUY        BUY  
2005        BUY        BUY  

[5 rows x 445 columns]

In [4]:
data['30_signal'].value_counts()
data.drop(index = data[data['30_signal']=='NONE'].index, inplace = True)

In [5]:
df = data.iloc[:,5:430] #datamızdan _signal kolonlarını attık
df.shape

(19440, 425)

In [6]:
#categorical olan kolonlarımız
cat_column_names = ['ind_7','ind_11','ind_24','ind_38','ind_54','ind_57','ind_60','ind_63','ind_66','ind_69','ind_72','ind_75',
                    'ind_78','ind_81','ind_84','ind_87','ind_89','ind_91','ind_93','ind_95','ind_97','ind_99','ind_101',
                    'ind_103','ind_105','ind_107','ind_109', 'ind_111', 'ind_113', 'ind_115','ind_138','ind_141','ind_144',
                    'ind_157','ind_159','ind_161','ind_163','ind_165','ind_167','ind_169','ind_171','ind_173','ind_175',
                    'ind_177','ind_182','ind_184','ind_187','ind_190','ind_193','ind_196','ind_199','ind_202','ind_205',
                    'ind_208','ind_211','ind_213','ind_384','ind_386','ind_388','ind_390']

In [7]:
# categorical kolonların dummy var. oalrak değiştirdik
dms = pd.get_dummies(df[cat_column_names])
dms_none_cols = dms.filter(regex = '_NONE').columns
for i in dms_none_cols:
    dms.drop(i,axis=1,inplace=True)
dms_red_cols = dms.filter(regex = '_RED').columns
for i in dms_red_cols:
    dms.drop(i,axis=1,inplace=True)

dms.head()

ind_7_BUY  ind_7_SELL  ind_11_BUY  ind_11_SELL  ind_24_BUY  ind_24_SELL  \
2001          0           0           0            1           1            0   
2002          0           0           0            1           1            0   
2003          1           0           0            1           1            0   
2004          0           0           0            1           1            0   
2005          0           0           0            1           1            0   

      ind_38_BUY  ind_38_SELL  ind_54_BUY  ind_54_SELL  ...  ind_211_BUY  \
2001           1            0           0            1  ...            0   
2002           1            0           0            1  ...            0   
2003           1            0           0            1  ...            0   
2004           1            0           1            0  ...            0   
2005           1            0           1            0  ...            0   

      ind_211_SELL  ind_384_BUY  ind_384_SELL  ind_386_BUY  ind_386_SELL  \
2001             1            0             1            0             0   
2002             1            0             1            0             0   
2003             0            0             1            0             0   
2004             0            0             1            1             0   
2005             0            0             1            1             0   

      ind_388_BUY  ind_388_SELL  ind_390_BUY  ind_390_SELL  
2001            0             1            0             1  
2002            0             1            0             1  
2003            0             1            0             1  
2004            1             0            0             1  
2005            1             0            0             1  

[5 rows x 117 columns]

In [8]:
#datadan categorical olan kolonları çıkarıyoruz ve type nı değiştiriyoruz
df = df.drop(cat_column_names,axis=1).astype("float64")
df.head()

ind_5  ind_6      ind_8      ind_9     ind_10     ind_12     ind_13  \
2001  -20.0  -19.0   7.142857  92.857143 -85.714286  35.726149 -80.907026   
2002  -20.0  -20.0   0.000000  85.714286 -85.714286  35.416025 -83.358058   
2003  -19.0  -20.0  35.714286  78.571429 -42.857143  44.091954 -27.798750   
2004  -17.0  -19.0  28.571429  71.428571 -42.857143  45.700892 -19.814109   
2005  -13.0  -17.0  21.428571  64.285714 -42.857143  45.996248 -18.409036   

      ind_14  ind_15  ind_16  ...  ind_420  ind_421  ind_422  ind_423  \
2001    5.45    7.14    8.47  ...     73.0    -79.0    -99.0    202.0   
2002    4.95    6.28    8.02  ...     74.0    -78.0    -99.0    203.0   
2003    7.55    6.28    7.83  ...     65.0    -87.0   -107.0    195.0   
2004    8.70    6.44    7.43  ...     64.0    -88.0   -109.0    193.0   
2005    4.85    6.16    7.03  ...     63.0    -88.0   -109.0    193.0   

       ind_424   ind_425   ind_426   ind_427   ind_428   ind_429  
2001  0.290323  0.120805  0.537500  0.510815  0.320588  0.359703  
2002  1.000000  0.129496  0.560261  0.452514  0.312500  0.360372  
2003  0.931507  0.593103  0.533333  0.476357  0.344390  0.369380  
2004  0.950495  0.699387  0.492754  0.596421  0.383929  0.373567  
2005  1.000000  0.959016  0.503623  0.571730  0.386161  0.372810  

[5 rows x 365 columns]

In [9]:
#dummy e çevirdiğimiz datalar ile X imizi birleştiriyoruz
X = pd.concat([df,dms],axis=1)
X.head()

ind_5  ind_6      ind_8      ind_9     ind_10     ind_12     ind_13  \
2001  -20.0  -19.0   7.142857  92.857143 -85.714286  35.726149 -80.907026   
2002  -20.0  -20.0   0.000000  85.714286 -85.714286  35.416025 -83.358058   
2003  -19.0  -20.0  35.714286  78.571429 -42.857143  44.091954 -27.798750   
2004  -17.0  -19.0  28.571429  71.428571 -42.857143  45.700892 -19.814109   
2005  -13.0  -17.0  21.428571  64.285714 -42.857143  45.996248 -18.409036   

      ind_14  ind_15  ind_16  ...  ind_211_BUY  ind_211_SELL  ind_384_BUY  \
2001    5.45    7.14    8.47  ...            0             1            0   
2002    4.95    6.28    8.02  ...            0             1            0   
2003    7.55    6.28    7.83  ...            0             0            0   
2004    8.70    6.44    7.43  ...            0             0            0   
2005    4.85    6.16    7.03  ...            0             0            0   

      ind_384_SELL  ind_386_BUY  ind_386_SELL  ind_388_BUY  ind_388_SELL  \
2001             1            0             0            0             1   
2002             1            0             0            0             1   
2003             1            0             0            0             1   
2004             1            1             0            1             0   
2005             1            1             0            1             0   

      ind_390_BUY  ind_390_SELL  
2001            0             1  
2002            0             1  
2003            0             1  
2004            0             1  
2005            0             1  

[5 rows x 482 columns]

In [10]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
pca = PCA()
# pca = PCA(n_components= 5) n_components parametresi ile 5 yeni pca'e düşüreleceği bilgisini modele söyleyebiliriz. 
#-default olarak %100'e ulaşacak şekilde bulur.

In [11]:
X_pca = pca.fit_transform(scale(X))

In [12]:
arr = np.cumsum(np.round(pca.explained_variance_ratio_, decimals = 4)*100)
arr

array([26.54, 36.39, 41.87, 45.02, 47.86, 50.36, 52.44, 54.31, 56.  ,
       57.54, 58.94, 60.23, 61.42, 62.6 , 63.68, 64.69, 65.64, 66.52,
       67.37, 68.18, 68.92, 69.65, 70.37, 71.07, 71.75, 72.37, 72.96,
       73.55, 74.13, 74.68, 75.22, 75.74, 76.25, 76.76, 77.25, 77.72,
       78.18, 78.63, 79.06, 79.48, 79.88, 80.27, 80.65, 81.02, 81.37,
       81.7 , 82.03, 82.35, 82.67, 82.98, 83.26, 83.54, 83.81, 84.08,
       84.35, 84.61, 84.87, 85.13, 85.38, 85.63, 85.87, 86.11, 86.35,
       86.58, 86.81, 87.04, 87.27, 87.5 , 87.72, 87.94, 88.16, 88.37,
       88.58, 88.79, 88.99, 89.19, 89.39, 89.58, 89.77, 89.95, 90.13,
       90.31, 90.49, 90.66, 90.83, 91.  , 91.17, 91.33, 91.49, 91.65,
       91.81, 91.96, 92.1 , 92.24, 92.38, 92.52, 92.66, 92.79, 92.92,
       93.05, 93.18, 93.31, 93.43, 93.55, 93.67, 93.79, 93.91, 94.02,
       94.13, 94.24, 94.34, 94.44, 94.54, 94.64, 94.74, 94.84, 94.93,
       95.02, 95.11, 95.2 , 95.29, 95.38, 95.47, 95.55, 95.63, 95.71,
       95.79, 95.87,

In [13]:
# tmp'den büyük değerleri değişken olarak aldık tmp'den küçük sayısı +1 tane sonra tmpden büyük olanı elde etmiş oluruz
tmp = 95
num_var = sum((arr < tmp)) + 1 
num_var

118

In [14]:
X_reduced = pd.DataFrame(X_pca[:,0:num_var])
X_reduced.head()

0         1         2         3         4         5         6    \
0  10.780859  2.904395  0.591062 -0.373800  1.046676 -3.827874  1.381419   
1  10.993491  1.427256  2.410482 -1.112891  0.245006 -3.179774  0.572505   
2   6.184159 -4.178447  7.217729 -1.412377  0.177093 -3.907146  0.869959   
3   3.784100 -6.381228  5.746491  0.661823 -0.301790 -3.995421  0.676569   
4   2.634021 -6.724007  3.553887  1.664987 -0.493581 -4.075789  0.585336   

        7         8         9    ...       108       109       110       111  \
0  3.868398  0.946496 -3.943905  ...  1.210327  0.900953  0.567495 -0.622563   
1  2.216690  0.502780 -3.868682  ...  0.298822  0.388819  0.936979 -0.774748   
2  3.673733  0.516124 -3.393015  ...  1.119707 -0.566419  0.752553  0.170053   
3  1.249901  2.267377 -4.501106  ...  1.496628 -0.930528  1.220889 -0.321078   
4  0.445006  3.061839 -4.939469  ...  0.585132  0.070163  0.929542 -0.186313   

        112       113       114       115       116       117  
0 -0.827410  0.099863  0.303472 -1.985718  0.454296 -0.269595  
1 -0.710008 -0.605261  0.017302 -0.797313  0.247512 -0.050911  
2 -0.451408  0.762720  0.360722 -0.459708  0.224448 -0.191856  
3 -0.542789 -0.822217  1.189392 -0.660633 -0.457395 -0.158170  
4 -0.426610 -0.352185  0.131278 -1.115298 -0.866859  0.215096  

[5 rows x 118 columns]

In [15]:
#logistic regresyon için y değişkenimizi 0 1 olarak değiştiriyoruz
data_y = data['30_signal']
cleanup_nums = {'BUY':1,'SELL':0}
data_y.replace(cleanup_nums, inplace=True)
y = np.array(data_y)
y

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
loj = sm.Logit(y, X_reduced)
loj_model = loj.fit()
loj_model.summary()

Optimization terminated successfully.
         Current function value: 0.676993
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                19440
Model:                          Logit   Df Residuals:                    19322
Method:                           MLE   Df Model:                          117
Date:                Sat, 05 Oct 2019   Pseudo R-squ.:                 0.02319
Time:                        10:37:38   Log-Likelihood:                -13161.
converged:                       True   LL-Null:                       -13473.
Covariance Type:            nonrobust   LLR p-value:                 2.214e-70
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
0             -0.0065      0.001     -4.802      0.000      -0.009      -0.004
1              0.0108      0.002      4.829      0.000       0.006       0.015
2              0.0038      0.003      1.266      0.206      -0.002       0.010
3              0.0071      0.004      1.790      0.073      -0.001       0.015
4              0.0080      0.004      1.889      0.059      -0.000       0.016
5              0.0082      0.004      1.833      0.067      -0.001       0.017
6              0.0062      0.005      1.261      0.207      -0.003       0.016
7             -0.0082      0.005     -1.596      0.111      -0.018       0.002
8             -0.0122      0.005     -2.236      0.025      -0.023      -0.002
9              0.0053      0.006      0.920      0.358      -0.006       0.016
10            -0.0127      0.006     -2.132      0.033      -0.024      -0.001
11             0.0263      0.006      4.224      0.000       0.014       0.038
12             0.0251      0.006      3.889      0.000       0.012       0.038
13             0.0097      0.007      1.486      0.137      -0.003       0.023
14            -0.0242      0.007     -3.540      0.000      -0.038      -0.011
15             0.0015      0.007      0.217      0.828      -0.012       0.015
16            -0.0027      0.007     -0.375      0.708      -0.017       0.011
17             0.0190      0.008      2.494      0.013       0.004       0.034
18            -0.0195      0.008     -2.554      0.011      -0.035      -0.005
19            -0.0068      0.008     -0.869      0.385      -0.022       0.008
20             0.0018      0.008      0.225      0.822      -0.014       0.018
21            -0.0109      0.008     -1.325      0.185      -0.027       0.005
22             0.0075      0.008      0.903      0.366      -0.009       0.024
23             0.0331      0.008      3.924      0.000       0.017       0.050
24            -0.0353      0.009     -4.138      0.000      -0.052      -0.019
25             0.0035      0.009      0.396      0.692      -0.014       0.021
26            -0.0051      0.009     -0.548      0.584      -0.023       0.013
27             0.0402      0.009      4.371      0.000       0.022       0.058
28            -0.0349      0.009     -3.783      0.000      -0.053      -0.017
29            -0.0157      0.009     -1.659      0.097      -0.034       0.003
30             0.0461      0.010      4.829      0.000       0.027       0.065
31             0.0061      0.010      0.625      0.532      -0.013       0.025
32             0.0227      0.010      2.319      0.020       0.004       0.042
33             0.0060      0.010      0.602      0.547      -0.013       0.025
34             0.0106      0.010      1.048      0.295      -0.009       0.030
35             0.0387      0.010      3.792      0.000       0.019       0.059
36            -0.0084      0.010     -0.814      0.416      -0.029       0.012
37             0.0327      0.011      3.107      0.002       0.012       0.053
38

In [17]:
from sklearn.linear_model import LogisticRegression
loj = LogisticRegression(solver = 'liblinear')
loj_model = loj.fit(X_reduced,y)
loj_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred = loj_model.predict(X_reduced)
confusion_mat = confusion_matrix(y, y_pred)
accuracy = accuracy_score(y, y_pred)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

Counfusion matrix: 
 [[5944 3899]
 [4500 5097]]
Accuracy:  0.5679526748971193


In [19]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.57      0.60      0.59      9843
           1       0.57      0.53      0.55      9597

    accuracy                           0.57     19440
   macro avg       0.57      0.57      0.57     19440
weighted avg       0.57      0.57      0.57     19440



In [20]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, shuffle = False)

In [21]:
pca1 = PCA()
pca2 = PCA()

In [22]:
X_train_pca = pca1.fit_transform(scale(X_train))
X_test_pca = pca2.fit_transform(scale(X_test))

In [23]:
arr1 = np.cumsum(np.round(pca1.explained_variance_ratio_, decimals = 4)*100)
arr2 = np.cumsum(np.round(pca2.explained_variance_ratio_, decimals = 4)*100)

In [24]:
# tmp'den büyük değerleri değişken olarak aldık tmp'den küçük sayısı +1 tane sonra tmpden büyük olanı elde etmiş oluruz
tmp = 0.95
num_var1 = sum((arr1 < tmp*100)) + 1 
num_var2 = sum((arr2 < tmp*100)) + 1 
print(num_var1, num_var2)

112 111


In [25]:
X_train_reduced = pd.DataFrame(X_train_pca[:,0:num_var1])
X_test_reduced = pd.DataFrame(X_test_pca[:,0:num_var2])

In [26]:
loj1 = LogisticRegression(solver = 'liblinear')
loj1_model = loj1.fit(X_train_reduced,y_train)
loj1_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
y_pred_1 = loj1_model.predict(X_train_reduced)
confusion_mat = confusion_matrix(y_train, y_pred_1)
accuracy = accuracy_score(y_train, y_pred_1)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

Counfusion matrix: 
 [[3852 2906]
 [2922 3928]]
Accuracy:  0.5717225161669606


In [28]:
print(classification_report(y_train, y_pred_1))

              precision    recall  f1-score   support

           0       0.57      0.57      0.57      6758
           1       0.57      0.57      0.57      6850

    accuracy                           0.57     13608
   macro avg       0.57      0.57      0.57     13608
weighted avg       0.57      0.57      0.57     13608



In [33]:
loj2 = LogisticRegression(solver = 'liblinear')
loj2_model = loj2.fit(X_test_reduced,y_test)
loj2_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
y_pred_2 = loj2_model.predict(X_test_reduced)
confusion_mat = confusion_matrix(y_test, y_pred_2)
accuracy = accuracy_score(y_test, y_pred_2)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

Counfusion matrix: 
 [[2164  921]
 [1212 1535]]
Accuracy:  0.6342592592592593


In [39]:
data.loc['date'].['2007']

SyntaxError: invalid syntax (<ipython-input-39-17b7e5f38ae3>, line 1)